name: Test and Lint

# Controls when the action will run. 
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

env:
  CI: true

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: npm install
        run: npm install

      - name: Lint (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint

      - name: Testing
        run: npm test -- --ci
