name: Lint

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  CI: true

jobs:
  test:
    name: Lint on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: npm install
        run: npm install

      - name: Lint (Linux/Node v14 only)
        if: (matrix.os == 'ubuntu-latest') && matrix.node-version == 14
        run: npm run lint
