name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is being marked as stale due to inactivity. To avoid it being closed please update it."
          stale-pr-message: "This pull request is being marked as stale due to inactivity. To avoid it being closed please update it."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
